package com.n2cj.entity;

// Generated 2015-10-15 18:23:01 by Hibernate Tools 4.3.1

/**
 * DicWare generated by hbm2java
 */
public class DicWare implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4470121929602773341L;
    private String id;
    private String code;
    private String name;
    private String type;
    private String order;

    public DicWare() {
    }

    public DicWare(String id, String code, String name, String type,
            String order) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.type = type;
        this.order = order;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOrder() {
        return this.order;
    }

    public void setOrder(String order) {
        this.order = order;
    }

}
