package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Editor generated by hbm2java
 */
public class Editor implements java.io.Serializable {

    private Integer editorId;
    private String editorTelephone;
    private String editorPassword;
    private String editorEmail;
    private String editorName;
    private String editorQq;
    private String editorSign;
    private String editorGender;
    private String editorOccupation;
    private String editorInterests;
    private Date editorBirth;
    private String editorAvatar;
    private int editorUnreadMsg;
    private byte[] editorNews;
    private int editorNewsAmount;
    private byte[] editorLive;
    private int editorLiveAmount;
    private String status;
    private Date addtime;
    private Date updatetime;
    private Set editorRoleRels = new HashSet(0);
    private Set newses = new HashSet(0);
    private Set lives = new HashSet(0);

    public Editor() {
    }

    public Editor(String editorPassword, String editorName,
                  int editorUnreadMsg, int editorNewsAmount, int editorLiveAmount,
                  String status, Date addtime, Date updatetime) {
        this.editorPassword = editorPassword;
        this.editorName = editorName;
        this.editorUnreadMsg = editorUnreadMsg;
        this.editorNewsAmount = editorNewsAmount;
        this.editorLiveAmount = editorLiveAmount;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Editor(String editorTelephone, String editorPassword,
                  String editorEmail, String editorName, String editorQq,
                  String editorSign, String editorGender, String editorOccupation,
                  String editorInterests, Date editorBirth, String editorAvatar,
                  int editorUnreadMsg, byte[] editorNews, int editorNewsAmount,
                  byte[] editorLive, int editorLiveAmount, String status,
                  Date addtime, Date updatetime, Set editorRoleRels, Set newses,
                  Set lives) {
        this.editorTelephone = editorTelephone;
        this.editorPassword = editorPassword;
        this.editorEmail = editorEmail;
        this.editorName = editorName;
        this.editorQq = editorQq;
        this.editorSign = editorSign;
        this.editorGender = editorGender;
        this.editorOccupation = editorOccupation;
        this.editorInterests = editorInterests;
        this.editorBirth = editorBirth;
        this.editorAvatar = editorAvatar;
        this.editorUnreadMsg = editorUnreadMsg;
        this.editorNews = editorNews;
        this.editorNewsAmount = editorNewsAmount;
        this.editorLive = editorLive;
        this.editorLiveAmount = editorLiveAmount;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.editorRoleRels = editorRoleRels;
        this.newses = newses;
        this.lives = lives;
    }

    public Integer getEditorId() {
        return this.editorId;
    }

    public void setEditorId(Integer editorId) {
        this.editorId = editorId;
    }

    public String getEditorTelephone() {
        return this.editorTelephone;
    }

    public void setEditorTelephone(String editorTelephone) {
        this.editorTelephone = editorTelephone;
    }

    public String getEditorPassword() {
        return this.editorPassword;
    }

    public void setEditorPassword(String editorPassword) {
        this.editorPassword = editorPassword;
    }

    public String getEditorEmail() {
        return this.editorEmail;
    }

    public void setEditorEmail(String editorEmail) {
        this.editorEmail = editorEmail;
    }

    public String getEditorName() {
        return this.editorName;
    }

    public void setEditorName(String editorName) {
        this.editorName = editorName;
    }

    public String getEditorQq() {
        return this.editorQq;
    }

    public void setEditorQq(String editorQq) {
        this.editorQq = editorQq;
    }

    public String getEditorSign() {
        return this.editorSign;
    }

    public void setEditorSign(String editorSign) {
        this.editorSign = editorSign;
    }

    public String getEditorGender() {
        return this.editorGender;
    }

    public void setEditorGender(String editorGender) {
        this.editorGender = editorGender;
    }

    public String getEditorOccupation() {
        return this.editorOccupation;
    }

    public void setEditorOccupation(String editorOccupation) {
        this.editorOccupation = editorOccupation;
    }

    public String getEditorInterests() {
        return this.editorInterests;
    }

    public void setEditorInterests(String editorInterests) {
        this.editorInterests = editorInterests;
    }

    public Date getEditorBirth() {
        return this.editorBirth;
    }

    public void setEditorBirth(Date editorBirth) {
        this.editorBirth = editorBirth;
    }

    public String getEditorAvatar() {
        return this.editorAvatar;
    }

    public void setEditorAvatar(String editorAvatar) {
        this.editorAvatar = editorAvatar;
    }

    public int getEditorUnreadMsg() {
        return this.editorUnreadMsg;
    }

    public void setEditorUnreadMsg(int editorUnreadMsg) {
        this.editorUnreadMsg = editorUnreadMsg;
    }

    public byte[] getEditorNews() {
        return this.editorNews;
    }

    public void setEditorNews(byte[] editorNews) {
        this.editorNews = editorNews;
    }

    public int getEditorNewsAmount() {
        return this.editorNewsAmount;
    }

    public void setEditorNewsAmount(int editorNewsAmount) {
        this.editorNewsAmount = editorNewsAmount;
    }

    public byte[] getEditorLive() {
        return this.editorLive;
    }

    public void setEditorLive(byte[] editorLive) {
        this.editorLive = editorLive;
    }

    public int getEditorLiveAmount() {
        return this.editorLiveAmount;
    }

    public void setEditorLiveAmount(int editorLiveAmount) {
        this.editorLiveAmount = editorLiveAmount;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Set getEditorRoleRels() {
        return this.editorRoleRels;
    }

    public void setEditorRoleRels(Set editorRoleRels) {
        this.editorRoleRels = editorRoleRels;
    }

    public Set getNewses() {
        return this.newses;
    }

    public void setNewses(Set newses) {
        this.newses = newses;
    }

    public Set getLives() {
        return this.lives;
    }

    public void setLives(Set lives) {
        this.lives = lives;
    }

}
