package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EditorRole generated by hbm2java
 */
public class EditorRole implements java.io.Serializable {

    private Integer roleId;
    private String roleName;
    private String roleDesc;
    private String status;
    private Date addtime;
    private Date updatetime;
    private String roleCode;
    private Set editorRoleRels = new HashSet(0);
    private Set editorroleEditorauthorityRels = new HashSet(0);

    public EditorRole() {
    }

    public EditorRole(String roleName, String status, Date addtime,
                      Date updatetime, String roleCode) {
        this.roleName = roleName;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.roleCode = roleCode;
    }

    public EditorRole(String roleName, String roleDesc, String status,
                      Date addtime, Date updatetime, String roleCode, Set editorRoleRels,
                      Set editorroleEditorauthorityRels) {
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.roleCode = roleCode;
        this.editorRoleRels = editorRoleRels;
        this.editorroleEditorauthorityRels = editorroleEditorauthorityRels;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleDesc() {
        return this.roleDesc;
    }

    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getRoleCode() {
        return this.roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public Set getEditorRoleRels() {
        return this.editorRoleRels;
    }

    public void setEditorRoleRels(Set editorRoleRels) {
        this.editorRoleRels = editorRoleRels;
    }

    public Set getEditorroleEditorauthorityRels() {
        return this.editorroleEditorauthorityRels;
    }

    public void setEditorroleEditorauthorityRels(
            Set editorroleEditorauthorityRels) {
        this.editorroleEditorauthorityRels = editorroleEditorauthorityRels;
    }

}
