package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * EditorRoleRel generated by hbm2java
 */
public class EditorRoleRel implements java.io.Serializable {

    private EditorRoleRelId id;
    private Editor editor;
    private EditorRole editorRole;

    public EditorRoleRel() {
    }

    public EditorRoleRel(EditorRoleRelId id, Editor editor,
                         EditorRole editorRole) {
        this.id = id;
        this.editor = editor;
        this.editorRole = editorRole;
    }

    public EditorRoleRelId getId() {
        return this.id;
    }

    public void setId(EditorRoleRelId id) {
        this.id = id;
    }

    public Editor getEditor() {
        return this.editor;
    }

    public void setEditor(Editor editor) {
        this.editor = editor;
    }

    public EditorRole getEditorRole() {
        return this.editorRole;
    }

    public void setEditorRole(EditorRole editorRole) {
        this.editorRole = editorRole;
    }

}
