package com.n2cj.entity;

// Generated 2015-9-24 22:05:14 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FinanceEvent generated by hbm2java
 */
public class FinanceEvent implements java.io.Serializable {

    private Integer eventId;
    private String eventStatus;
    private String eventType;
    private String eventCountry;
    private String eventRegion;
    private Date eventPublishTime;
    private String eventImportance;
    private String eventContent;
    private String eventTitle;
    private String eventLink;
    private Date eventAddTime;
    private Date eventModifyTime;

    public FinanceEvent() {
    }

    public FinanceEvent(String eventStatus, String eventType, String eventCountry,
                        String eventRegion, Date eventPublishTime, String eventImportance,
                        String eventContent, String eventTitle, String eventLink, Date eventAddTime,
                        Date eventModifyTime) {
        this.eventStatus = eventStatus;
        this.eventType = eventType;
        this.eventCountry = eventCountry;
        this.eventRegion = eventRegion;
        this.eventPublishTime = eventPublishTime;
        this.eventImportance = eventImportance;
        this.eventContent = eventContent;
        this.eventTitle = eventTitle;
        this.eventLink = eventLink;
        this.eventAddTime = eventAddTime;
        this.eventModifyTime = eventModifyTime;
    }

    public Integer getEventId() {
        return this.eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    public String getEventStatus() {
        return this.eventStatus;
    }

    public void setEventStatus(String eventStatus) {
        this.eventStatus = eventStatus;
    }

    public String getEventType() {
        return this.eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getEventCountry() {
        return this.eventCountry;
    }

    public void setEventCountry(String eventCountry) {
        this.eventCountry = eventCountry;
    }

    public String getEventRegion() {
        return this.eventRegion;
    }

    public void setEventRegion(String eventRegion) {
        this.eventRegion = eventRegion;
    }

    public Date getEventPublishTime() {
        return this.eventPublishTime;
    }

    public void setEventPublishTime(Date eventPublishTime) {
        this.eventPublishTime = eventPublishTime;
    }

    public String getEventImportance() {
        return this.eventImportance;
    }

    public void setEventImportance(String eventImportance) {
        this.eventImportance = eventImportance;
    }

    public String getEventContent() {
        return this.eventContent;
    }

    public void setEventContent(String eventContent) {
        this.eventContent = eventContent;
    }

    public String getEventTitle() {
        return this.eventTitle;
    }

    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }

    public String getEventLink() {
        return this.eventLink;
    }

    public void setEventLink(String eventLink) {
        this.eventLink = eventLink;
    }

    public Date getEventAddTime() {
        return this.eventAddTime;
    }

    public void setEventAddTime(Date eventAddTime) {
        this.eventAddTime = eventAddTime;
    }

    public Date getEventModifyTime() {
        return this.eventModifyTime;
    }

    public void setEventModifyTime(Date eventModifyTime) {
        this.eventModifyTime = eventModifyTime;
    }

}
