package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Holidy generated by hbm2java
 */
public class Holidy implements java.io.Serializable {

    private Integer holidayId;
    private String holidayStatus;
    private Date holidayPublishTime;
    private String holidayCountry;
    private String holidayRegion;
    private String holidayImportance;
    private String holidayContent;
    private String holidayTitle;
    private Date holidayAddTime;
    private Date holidayModifyTime;

    public Holidy() {
    }

    public Holidy(String holidayStatus, Date holidayPublishTime,
                  String holidayCountry, String holidayRegion,
                  String holidayImportance, String holidayContent,
                  String holidayTitle, Date holidayAddTime, Date holidayModifyTime) {
        this.holidayStatus = holidayStatus;
        this.holidayPublishTime = holidayPublishTime;
        this.holidayCountry = holidayCountry;
        this.holidayRegion = holidayRegion;
        this.holidayImportance = holidayImportance;
        this.holidayContent = holidayContent;
        this.holidayTitle = holidayTitle;
        this.holidayAddTime = holidayAddTime;
        this.holidayModifyTime = holidayModifyTime;
    }

    public Integer getHolidayId() {
        return this.holidayId;
    }

    public void setHolidayId(Integer holidayId) {
        this.holidayId = holidayId;
    }

    public String getHolidayStatus() {
        return this.holidayStatus;
    }

    public void setHolidayStatus(String holidayStatus) {
        this.holidayStatus = holidayStatus;
    }

    public Date getHolidayPublishTime() {
        return this.holidayPublishTime;
    }

    public void setHolidayPublishTime(Date holidayPublishTime) {
        this.holidayPublishTime = holidayPublishTime;
    }

    public String getHolidayCountry() {
        return this.holidayCountry;
    }

    public void setHolidayCountry(String holidayCountry) {
        this.holidayCountry = holidayCountry;
    }

    public String getHolidayRegion() {
        return this.holidayRegion;
    }

    public void setHolidayRegion(String holidayRegion) {
        this.holidayRegion = holidayRegion;
    }

    public String getHolidayImportance() {
        return this.holidayImportance;
    }

    public void setHolidayImportance(String holidayImportance) {
        this.holidayImportance = holidayImportance;
    }

    public String getHolidayContent() {
        return this.holidayContent;
    }

    public void setHolidayContent(String holidayContent) {
        this.holidayContent = holidayContent;
    }

    public String getHolidayTitle() {
        return this.holidayTitle;
    }

    public void setHolidayTitle(String holidayTitle) {
        this.holidayTitle = holidayTitle;
    }

    public Date getHolidayAddTime() {
        return this.holidayAddTime;
    }

    public void setHolidayAddTime(Date holidayAddTime) {
        this.holidayAddTime = holidayAddTime;
    }

    public Date getHolidayModifyTime() {
        return this.holidayModifyTime;
    }

    public void setHolidayModifyTime(Date holidayModifyTime) {
        this.holidayModifyTime = holidayModifyTime;
    }

}
