package com.n2cj.entity;

// Generated 2015-11-4 13:47:59 by Hibernate Tools 4.3.1

/**
 * Hotrecommend generated by hbm2java
 */
public class Hotrecommend implements java.io.Serializable {

	private Integer hotrecommendId;
	private String hotrecommendStatus;
	private String hotrecommendText;
	private String hotrecommendRank;
	private String hotrecommendLink;

	public Hotrecommend() {
	}

	public Hotrecommend(String hotrecommendStatus, String hotrecommendText,
			String hotrecommendRank, String hotrecommendLink) {
		this.hotrecommendStatus = hotrecommendStatus;
		this.hotrecommendText = hotrecommendText;
		this.hotrecommendRank = hotrecommendRank;
		this.hotrecommendLink = hotrecommendLink;
	}

	public Integer getHotrecommendId() {
		return this.hotrecommendId;
	}

	public void setHotrecommendId(Integer hotrecommendId) {
		this.hotrecommendId = hotrecommendId;
	}

	public String getHotrecommendStatus() {
		return this.hotrecommendStatus;
	}

	public void setHotrecommendStatus(String hotrecommendStatus) {
		this.hotrecommendStatus = hotrecommendStatus;
	}

	public String getHotrecommendText() {
		return this.hotrecommendText;
	}

	public void setHotrecommendText(String hotrecommendText) {
		this.hotrecommendText = hotrecommendText;
	}

	public String getHotrecommendRank() {
		return this.hotrecommendRank;
	}

	public void setHotrecommendRank(String hotrecommendRank) {
		this.hotrecommendRank = hotrecommendRank;
	}

	public String getHotrecommendLink() {
		return this.hotrecommendLink;
	}

	public void setHotrecommendLink(String hotrecommendLink) {
		this.hotrecommendLink = hotrecommendLink;
	}

}
