package com.n2cj.entity;

// Generated 2015-11-4 13:47:59 by Hibernate Tools 4.3.1

/**
 * Hotword generated by hbm2java
 */
public class Hotword implements java.io.Serializable {

	private Integer hotwordId;
	private String hotwordStatus;
	private String hotwordText;
	private String hotwordRank;
	private String hotwordLink;

	public Hotword() {
	}

	public Hotword(String hotwordStatus, String hotwordText,
			String hotwordRank, String hotwordLink) {
		this.hotwordStatus = hotwordStatus;
		this.hotwordText = hotwordText;
		this.hotwordRank = hotwordRank;
		this.hotwordLink = hotwordLink;
	}

	public Integer getHotwordId() {
		return this.hotwordId;
	}

	public void setHotwordId(Integer hotwordId) {
		this.hotwordId = hotwordId;
	}

	public String getHotwordStatus() {
		return this.hotwordStatus;
	}

	public void setHotwordStatus(String hotwordStatus) {
		this.hotwordStatus = hotwordStatus;
	}

	public String getHotwordText() {
		return this.hotwordText;
	}

	public void setHotwordText(String hotwordText) {
		this.hotwordText = hotwordText;
	}

	public String getHotwordRank() {
		return this.hotwordRank;
	}

	public void setHotwordRank(String hotwordRank) {
		this.hotwordRank = hotwordRank;
	}

	public String getHotwordLink() {
		return this.hotwordLink;
	}

	public void setHotwordLink(String hotwordLink) {
		this.hotwordLink = hotwordLink;
	}

}
