package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Live generated by hbm2java
 */
public class Live implements java.io.Serializable {

    private Integer liveId;
    private Editor editor;
    private byte[] liveTitle;
    private Integer liveImportance;
    private boolean liveIsChangedToNews;
    private Integer newsId;
    private String liveTagList;
    private String status;
    private Date addtime;
    private Date updatetime;
    private byte[] liveText;
    private String liveUrl;
    private Set tagLiveRels = new HashSet(0);

    public Live() {
    }

    public Live(Editor editor, byte[] liveTitle, boolean liveIsChangedToNews,
                String status, Date addtime, Date updatetime, String liveUrl) {
        this.editor = editor;
        this.liveTitle = liveTitle;
        this.liveIsChangedToNews = liveIsChangedToNews;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.liveUrl = liveUrl;
    }

    public Live(Editor editor, byte[] liveTitle, Integer liveImportance,
                boolean liveIsChangedToNews, Integer newsId, String liveTagList,
                String status, Date addtime, Date updatetime, byte[] liveText,
                String liveUrl, Set tagLiveRels) {
        this.editor = editor;
        this.liveTitle = liveTitle;
        this.liveImportance = liveImportance;
        this.liveIsChangedToNews = liveIsChangedToNews;
        this.newsId = newsId;
        this.liveTagList = liveTagList;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.liveText = liveText;
        this.liveUrl = liveUrl;
        this.tagLiveRels = tagLiveRels;
    }

    public Integer getLiveId() {
        return this.liveId;
    }

    public void setLiveId(Integer liveId) {
        this.liveId = liveId;
    }

    public Editor getEditor() {
        return this.editor;
    }

    public void setEditor(Editor editor) {
        this.editor = editor;
    }

    public byte[] getLiveTitle() {
        return this.liveTitle;
    }

    public void setLiveTitle(byte[] liveTitle) {
        this.liveTitle = liveTitle;
    }

    public Integer getLiveImportance() {
        return this.liveImportance;
    }

    public void setLiveImportance(Integer liveImportance) {
        this.liveImportance = liveImportance;
    }

    public boolean isLiveIsChangedToNews() {
        return this.liveIsChangedToNews;
    }

    public void setLiveIsChangedToNews(boolean liveIsChangedToNews) {
        this.liveIsChangedToNews = liveIsChangedToNews;
    }

    public Integer getNewsId() {
        return this.newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public String getLiveTagList() {
        return this.liveTagList;
    }

    public void setLiveTagList(String liveTagList) {
        this.liveTagList = liveTagList;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public byte[] getLiveText() {
        return this.liveText;
    }

    public void setLiveText(byte[] liveText) {
        this.liveText = liveText;
    }

    public String getLiveUrl() {
        return this.liveUrl;
    }

    public void setLiveUrl(String liveUrl) {
        this.liveUrl = liveUrl;
    }

    public Set getTagLiveRels() {
        return this.tagLiveRels;
    }

    public void setTagLiveRels(Set tagLiveRels) {
        this.tagLiveRels = tagLiveRels;
    }

}
