package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NationalDebt generated by hbm2java
 */
public class NationalDebt implements java.io.Serializable {

    private Integer debtId;
    private String debtStatus;
    private Date debtPublishTime;
    private String debtCountry;
    private String debtRegion;
    private String debtImportance;
    private String debtContent;
    private Date debtAddTime;
    private Date debtModifyTime;

    public NationalDebt() {
    }

    public NationalDebt(String debtStatus, Date debtPublishTime,
                        String debtCountry, String debtRegion, String debtImportance,
                        String debtContent, Date debtAddTime, Date debtModifyTime) {
        this.debtStatus = debtStatus;
        this.debtPublishTime = debtPublishTime;
        this.debtCountry = debtCountry;
        this.debtRegion = debtRegion;
        this.debtImportance = debtImportance;
        this.debtContent = debtContent;
        this.debtAddTime = debtAddTime;
        this.debtModifyTime = debtModifyTime;
    }

    public Integer getDebtId() {
        return this.debtId;
    }

    public void setDebtId(Integer debtId) {
        this.debtId = debtId;
    }

    public String getDebtStatus() {
        return this.debtStatus;
    }

    public void setDebtStatus(String debtStatus) {
        this.debtStatus = debtStatus;
    }

    public Date getDebtPublishTime() {
        return this.debtPublishTime;
    }

    public void setDebtPublishTime(Date debtPublishTime) {
        this.debtPublishTime = debtPublishTime;
    }

    public String getDebtCountry() {
        return this.debtCountry;
    }

    public void setDebtCountry(String debtCountry) {
        this.debtCountry = debtCountry;
    }

    public String getDebtRegion() {
        return this.debtRegion;
    }

    public void setDebtRegion(String debtRegion) {
        this.debtRegion = debtRegion;
    }

    public String getDebtImportance() {
        return this.debtImportance;
    }

    public void setDebtImportance(String debtImportance) {
        this.debtImportance = debtImportance;
    }

    public String getDebtContent() {
        return this.debtContent;
    }

    public void setDebtContent(String debtContent) {
        this.debtContent = debtContent;
    }

    public Date getDebtAddTime() {
        return this.debtAddTime;
    }

    public void setDebtAddTime(Date debtAddTime) {
        this.debtAddTime = debtAddTime;
    }

    public Date getDebtModifyTime() {
        return this.debtModifyTime;
    }

    public void setDebtModifyTime(Date debtModifyTime) {
        this.debtModifyTime = debtModifyTime;
    }

}
