package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * NewsViewRankDay generated by hbm2java
 */
public class NewsViewRankDay implements java.io.Serializable {

    private NewsViewRankDayId id;
    private News news;

    public NewsViewRankDay() {
    }

    public NewsViewRankDay(NewsViewRankDayId id, News news) {
        this.id = id;
        this.news = news;
    }

    public NewsViewRankDayId getId() {
        return this.id;
    }

    public void setId(NewsViewRankDayId id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

}
