package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NewsTop generated by hbm2java
 */
public class NewsTop implements java.io.Serializable {

    private Integer newsTopId;
    private News news;
    private String status;
    private Date addtime;
    private Date updatetime;

    public NewsTop() {
    }

    public NewsTop(News news, String status, Date addtime, Date updatetime) {
        this.news = news;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Integer getNewsTopId() {
        return this.newsTopId;
    }

    public void setNewsTopId(Integer newsTopId) {
        this.newsTopId = newsTopId;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

}
