package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * NewsViewRankWeek generated by hbm2java
 */
public class NewsViewRankWeek implements java.io.Serializable {

    private NewsViewRankWeekId id;
    private News news;

    public NewsViewRankWeek() {
    }

    public NewsViewRankWeek(NewsViewRankWeekId id, News news) {
        this.id = id;
        this.news = news;
    }

    public NewsViewRankWeekId getId() {
        return this.id;
    }

    public void setId(NewsViewRankWeekId id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

}
