package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NewsIndexPageTopId generated by hbm2java
 */
public class NewsIndexPageTopId implements java.io.Serializable {

    private int newsIndexPageId;
    private int newsId;
    private String newsTopImage;
    private Integer newsTopOrder;
    private String status;
    private Date addtime;
    private Date updatetime;

    public NewsIndexPageTopId() {
    }

    public NewsIndexPageTopId(int newsIndexPageId, int newsId, String status,
                              Date addtime, Date updatetime) {
        this.newsIndexPageId = newsIndexPageId;
        this.newsId = newsId;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public NewsIndexPageTopId(int newsIndexPageId, int newsId,
                              String newsTopImage, Integer newsTopOrder, String status,
                              Date addtime, Date updatetime) {
        this.newsIndexPageId = newsIndexPageId;
        this.newsId = newsId;
        this.newsTopImage = newsTopImage;
        this.newsTopOrder = newsTopOrder;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public int getNewsIndexPageId() {
        return this.newsIndexPageId;
    }

    public void setNewsIndexPageId(int newsIndexPageId) {
        this.newsIndexPageId = newsIndexPageId;
    }

    public int getNewsId() {
        return this.newsId;
    }

    public void setNewsId(int newsId) {
        this.newsId = newsId;
    }

    public String getNewsTopImage() {
        return this.newsTopImage;
    }

    public void setNewsTopImage(String newsTopImage) {
        this.newsTopImage = newsTopImage;
    }

    public Integer getNewsTopOrder() {
        return this.newsTopOrder;
    }

    public void setNewsTopOrder(Integer newsTopOrder) {
        this.newsTopOrder = newsTopOrder;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof NewsIndexPageTopId))
            return false;
        NewsIndexPageTopId castOther = (NewsIndexPageTopId) other;

        return (this.getNewsIndexPageId() == castOther.getNewsIndexPageId())
                && (this.getNewsId() == castOther.getNewsId())
                && ((this.getNewsTopImage() == castOther.getNewsTopImage()) || (this
                .getNewsTopImage() != null
                && castOther.getNewsTopImage() != null && this
                .getNewsTopImage().equals(castOther.getNewsTopImage())))
                && ((this.getNewsTopOrder() == castOther.getNewsTopOrder()) || (this
                .getNewsTopOrder() != null
                && castOther.getNewsTopOrder() != null && this
                .getNewsTopOrder().equals(castOther.getNewsTopOrder())))
                && ((this.getStatus() == castOther.getStatus()) || (this
                .getStatus() != null && castOther.getStatus() != null && this
                .getStatus().equals(castOther.getStatus())))
                && ((this.getAddtime() == castOther.getAddtime()) || (this
                .getAddtime() != null && castOther.getAddtime() != null && this
                .getAddtime().equals(castOther.getAddtime())))
                && ((this.getUpdatetime() == castOther.getUpdatetime()) || (this
                .getUpdatetime() != null
                && castOther.getUpdatetime() != null && this
                .getUpdatetime().equals(castOther.getUpdatetime())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getNewsIndexPageId();
        result = 37 * result + this.getNewsId();
        result = 37
                * result
                + (getNewsTopImage() == null ? 0 : this.getNewsTopImage()
                .hashCode());
        result = 37
                * result
                + (getNewsTopOrder() == null ? 0 : this.getNewsTopOrder()
                .hashCode());
        result = 37 * result
                + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result
                + (getAddtime() == null ? 0 : this.getAddtime().hashCode());
        result = 37
                * result
                + (getUpdatetime() == null ? 0 : this.getUpdatetime()
                .hashCode());
        return result;
    }

}
