package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * NewsViewRankMonth generated by hbm2java
 */
public class NewsViewRankMonth implements java.io.Serializable {

    private NewsViewRankMonthId id;
    private News news;

    public NewsViewRankMonth() {
    }

    public NewsViewRankMonth(NewsViewRankMonthId id, News news) {
        this.id = id;
        this.news = news;
    }

    public NewsViewRankMonthId getId() {
        return this.id;
    }

    public void setId(NewsViewRankMonthId id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

}
