package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NewsHeadline generated by hbm2java
 */
public class NewsHeadline implements java.io.Serializable {

    private Integer newsHeadlineId;
    private News news;
    private String status;
    private Date addtime;
    private Date updatetime;

    public NewsHeadline() {
    }

    public NewsHeadline(News news, String status, Date addtime, Date updatetime) {
        this.news = news;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Integer getNewsHeadlineId() {
        return this.newsHeadlineId;
    }

    public void setNewsHeadlineId(Integer newsHeadlineId) {
        this.newsHeadlineId = newsHeadlineId;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

}
