package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NewsIndexPage generated by hbm2java
 */
public class NewsIndexPage implements java.io.Serializable {

    private Integer newsIndexPageId;
    private String newsIndexHotTags;
    private String status;
    private Date addtime;
    private Date updatetime;
    private Set newsIndexPageTops = new HashSet(0);

    public NewsIndexPage() {
    }

    public NewsIndexPage(String newsIndexHotTags, String status, Date addtime,
                         Date updatetime) {
        this.newsIndexHotTags = newsIndexHotTags;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public NewsIndexPage(String newsIndexHotTags, String status, Date addtime,
                         Date updatetime, Set newsIndexPageTops) {
        this.newsIndexHotTags = newsIndexHotTags;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.newsIndexPageTops = newsIndexPageTops;
    }

    public Integer getNewsIndexPageId() {
        return this.newsIndexPageId;
    }

    public void setNewsIndexPageId(Integer newsIndexPageId) {
        this.newsIndexPageId = newsIndexPageId;
    }

    public String getNewsIndexHotTags() {
        return this.newsIndexHotTags;
    }

    public void setNewsIndexHotTags(String newsIndexHotTags) {
        this.newsIndexHotTags = newsIndexHotTags;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Set getNewsIndexPageTops() {
        return this.newsIndexPageTops;
    }

    public void setNewsIndexPageTops(Set newsIndexPageTops) {
        this.newsIndexPageTops = newsIndexPageTops;
    }

}
