package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NewsComment generated by hbm2java
 */
public class NewsComment implements java.io.Serializable {

    private Integer newsCommentId;
    private News news;
    private User user;
    private String newsCommentText;
    private String newsCommentIp;
    private Integer newsCommentQuote;
    private int newsCommentOrder;
    private String status;
    private Date addtime;
    private Date updatetime;

    public NewsComment() {
    }

    public NewsComment(News news, User user, String newsCommentText,
                       int newsCommentOrder, String status, Date addtime, Date updatetime) {
        this.news = news;
        this.user = user;
        this.newsCommentText = newsCommentText;
        this.newsCommentOrder = newsCommentOrder;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public NewsComment(News news, User user, String newsCommentText,
                       String newsCommentIp, Integer newsCommentQuote,
                       int newsCommentOrder, String status, Date addtime, Date updatetime) {
        this.news = news;
        this.user = user;
        this.newsCommentText = newsCommentText;
        this.newsCommentIp = newsCommentIp;
        this.newsCommentQuote = newsCommentQuote;
        this.newsCommentOrder = newsCommentOrder;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Integer getNewsCommentId() {
        return this.newsCommentId;
    }

    public void setNewsCommentId(Integer newsCommentId) {
        this.newsCommentId = newsCommentId;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNewsCommentText() {
        return this.newsCommentText;
    }

    public void setNewsCommentText(String newsCommentText) {
        this.newsCommentText = newsCommentText;
    }

    public String getNewsCommentIp() {
        return this.newsCommentIp;
    }

    public void setNewsCommentIp(String newsCommentIp) {
        this.newsCommentIp = newsCommentIp;
    }

    public Integer getNewsCommentQuote() {
        return this.newsCommentQuote;
    }

    public void setNewsCommentQuote(Integer newsCommentQuote) {
        this.newsCommentQuote = newsCommentQuote;
    }

    public int getNewsCommentOrder() {
        return this.newsCommentOrder;
    }

    public void setNewsCommentOrder(int newsCommentOrder) {
        this.newsCommentOrder = newsCommentOrder;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

}
