package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * NewsCategoryRel generated by hbm2java
 */
public class NewsCategoryRel implements java.io.Serializable {

    private NewsCategoryRelId id;
    private News news;
    private NewsCategory newsCategory;

    public NewsCategoryRel() {
    }

    public NewsCategoryRel(NewsCategoryRelId id, News news,
                           NewsCategory newsCategory) {
        this.id = id;
        this.news = news;
        this.newsCategory = newsCategory;
    }

    public NewsCategoryRelId getId() {
        return this.id;
    }

    public void setId(NewsCategoryRelId id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public NewsCategory getNewsCategory() {
        return this.newsCategory;
    }

    public void setNewsCategory(NewsCategory newsCategory) {
        this.newsCategory = newsCategory;
    }

}
