package com.n2cj.entity;

// Generated 2015-10-29 13:23:54 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer newsId;
	private Editor editor;
	private String newsCategoryList;
	private String newsTitle;
	private String newsAbstract;
	private byte[] newsText;
	private int newsView;
	private int newsLike;
	private int newsDislike;
	private int newsComment;
	private int newsForward;
	private int newsFollow;
	private boolean newsIsHeadline;
	private boolean newsIsTop;
	private boolean newsIsRecommend;
	private Integer newsImportance;
	private int newsWord;
	private boolean newsIsAd;
	private String newsAdImage;
	private String newsAdHref;
	private String newsTagList;
	private int newsViewMonth;
	private int newsViewWeek;
	private int newsViewDay;
	private Date newsViewDate;
	private String status;
	private Date addtime;
	private Date updatetime;
	private boolean newsIsOrigin;
	private String newsSource;
	private String newsAuthor;
	private String newsThumbnail;
	private String newsPath;
	private Integer newsPages;
	private Date publishtime;
	private Set newsViewRankMonths = new HashSet(0);
	private Set newsComments = new HashSet(0);
	private Set newsCategoryRels = new HashSet(0);
	private Set newsFollows = new HashSet(0);
	private Set newsViewRankWeeks = new HashSet(0);
	private Set newsViewRankDays = new HashSet(0);
	private Set newsLikes = new HashSet(0);
	private Set newsHeadlines = new HashSet(0);
	private Set newsForwards = new HashSet(0);
	private Set tagNewsRels = new HashSet(0);
	private Set newsTops = new HashSet(0);
	private Set newsIndexPageTops = new HashSet(0);

	public News() {
	}

	public News(Editor editor, String newsTitle, int newsView, int newsLike,
			int newsDislike, int newsComment, int newsForward, int newsFollow,
			boolean newsIsHeadline, boolean newsIsTop, boolean newsIsRecommend,
			int newsWord, boolean newsIsAd, String newsTagList,
			int newsViewMonth, int newsViewWeek, int newsViewDay,
			Date newsViewDate, String status, Date addtime, Date updatetime,
			boolean newsIsOrigin, Date publishtime) {
		this.editor = editor;
		this.newsTitle = newsTitle;
		this.newsView = newsView;
		this.newsLike = newsLike;
		this.newsDislike = newsDislike;
		this.newsComment = newsComment;
		this.newsForward = newsForward;
		this.newsFollow = newsFollow;
		this.newsIsHeadline = newsIsHeadline;
		this.newsIsTop = newsIsTop;
		this.newsIsRecommend = newsIsRecommend;
		this.newsWord = newsWord;
		this.newsIsAd = newsIsAd;
		this.newsTagList = newsTagList;
		this.newsViewMonth = newsViewMonth;
		this.newsViewWeek = newsViewWeek;
		this.newsViewDay = newsViewDay;
		this.newsViewDate = newsViewDate;
		this.status = status;
		this.addtime = addtime;
		this.updatetime = updatetime;
		this.newsIsOrigin = newsIsOrigin;
		this.publishtime = publishtime;
	}

	public News(Editor editor, String newsCategoryList, String newsTitle,
			String newsAbstract, byte[] newsText, int newsView, int newsLike,
			int newsDislike, int newsComment, int newsForward, int newsFollow,
			boolean newsIsHeadline, boolean newsIsTop, boolean newsIsRecommend,
			Integer newsImportance, int newsWord, boolean newsIsAd,
			String newsAdImage, String newsAdHref, String newsTagList,
			int newsViewMonth, int newsViewWeek, int newsViewDay,
			Date newsViewDate, String status, Date addtime, Date updatetime,
			boolean newsIsOrigin, String newsSource, String newsAuthor,
			String newsThumbnail, String newsPath, Integer newsPages,
			Date publishtime, Set newsViewRankMonths, Set newsComments,
			Set newsCategoryRels, Set newsFollows, Set newsViewRankWeeks,
			Set newsViewRankDays, Set newsLikes, Set newsHeadlines,
			Set newsForwards, Set tagNewsRels, Set newsTops,
			Set newsIndexPageTops) {
		this.editor = editor;
		this.newsCategoryList = newsCategoryList;
		this.newsTitle = newsTitle;
		this.newsAbstract = newsAbstract;
		this.newsText = newsText;
		this.newsView = newsView;
		this.newsLike = newsLike;
		this.newsDislike = newsDislike;
		this.newsComment = newsComment;
		this.newsForward = newsForward;
		this.newsFollow = newsFollow;
		this.newsIsHeadline = newsIsHeadline;
		this.newsIsTop = newsIsTop;
		this.newsIsRecommend = newsIsRecommend;
		this.newsImportance = newsImportance;
		this.newsWord = newsWord;
		this.newsIsAd = newsIsAd;
		this.newsAdImage = newsAdImage;
		this.newsAdHref = newsAdHref;
		this.newsTagList = newsTagList;
		this.newsViewMonth = newsViewMonth;
		this.newsViewWeek = newsViewWeek;
		this.newsViewDay = newsViewDay;
		this.newsViewDate = newsViewDate;
		this.status = status;
		this.addtime = addtime;
		this.updatetime = updatetime;
		this.newsIsOrigin = newsIsOrigin;
		this.newsSource = newsSource;
		this.newsAuthor = newsAuthor;
		this.newsThumbnail = newsThumbnail;
		this.newsPath = newsPath;
		this.newsPages = newsPages;
		this.publishtime = publishtime;
		this.newsViewRankMonths = newsViewRankMonths;
		this.newsComments = newsComments;
		this.newsCategoryRels = newsCategoryRels;
		this.newsFollows = newsFollows;
		this.newsViewRankWeeks = newsViewRankWeeks;
		this.newsViewRankDays = newsViewRankDays;
		this.newsLikes = newsLikes;
		this.newsHeadlines = newsHeadlines;
		this.newsForwards = newsForwards;
		this.tagNewsRels = tagNewsRels;
		this.newsTops = newsTops;
		this.newsIndexPageTops = newsIndexPageTops;
	}

	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	public Editor getEditor() {
		return this.editor;
	}

	public void setEditor(Editor editor) {
		this.editor = editor;
	}

	public String getNewsCategoryList() {
		return this.newsCategoryList;
	}

	public void setNewsCategoryList(String newsCategoryList) {
		this.newsCategoryList = newsCategoryList;
	}

	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public String getNewsAbstract() {
		return this.newsAbstract;
	}

	public void setNewsAbstract(String newsAbstract) {
		this.newsAbstract = newsAbstract;
	}

	public byte[] getNewsText() {
		return this.newsText;
	}

	public void setNewsText(byte[] newsText) {
		this.newsText = newsText;
	}

	public int getNewsView() {
		return this.newsView;
	}

	public void setNewsView(int newsView) {
		this.newsView = newsView;
	}

	public int getNewsLike() {
		return this.newsLike;
	}

	public void setNewsLike(int newsLike) {
		this.newsLike = newsLike;
	}

	public int getNewsDislike() {
		return this.newsDislike;
	}

	public void setNewsDislike(int newsDislike) {
		this.newsDislike = newsDislike;
	}

	public int getNewsComment() {
		return this.newsComment;
	}

	public void setNewsComment(int newsComment) {
		this.newsComment = newsComment;
	}

	public int getNewsForward() {
		return this.newsForward;
	}

	public void setNewsForward(int newsForward) {
		this.newsForward = newsForward;
	}

	public int getNewsFollow() {
		return this.newsFollow;
	}

	public void setNewsFollow(int newsFollow) {
		this.newsFollow = newsFollow;
	}

	public boolean isNewsIsHeadline() {
		return this.newsIsHeadline;
	}

	public void setNewsIsHeadline(boolean newsIsHeadline) {
		this.newsIsHeadline = newsIsHeadline;
	}

	public boolean isNewsIsTop() {
		return this.newsIsTop;
	}

	public void setNewsIsTop(boolean newsIsTop) {
		this.newsIsTop = newsIsTop;
	}

	public boolean isNewsIsRecommend() {
		return this.newsIsRecommend;
	}

	public void setNewsIsRecommend(boolean newsIsRecommend) {
		this.newsIsRecommend = newsIsRecommend;
	}

	public Integer getNewsImportance() {
		return this.newsImportance;
	}

	public void setNewsImportance(Integer newsImportance) {
		this.newsImportance = newsImportance;
	}

	public int getNewsWord() {
		return this.newsWord;
	}

	public void setNewsWord(int newsWord) {
		this.newsWord = newsWord;
	}

	public boolean isNewsIsAd() {
		return this.newsIsAd;
	}

	public void setNewsIsAd(boolean newsIsAd) {
		this.newsIsAd = newsIsAd;
	}

	public String getNewsAdImage() {
		return this.newsAdImage;
	}

	public void setNewsAdImage(String newsAdImage) {
		this.newsAdImage = newsAdImage;
	}

	public String getNewsAdHref() {
		return this.newsAdHref;
	}

	public void setNewsAdHref(String newsAdHref) {
		this.newsAdHref = newsAdHref;
	}

	public String getNewsTagList() {
		return this.newsTagList;
	}

	public void setNewsTagList(String newsTagList) {
		this.newsTagList = newsTagList;
	}

	public int getNewsViewMonth() {
		return this.newsViewMonth;
	}

	public void setNewsViewMonth(int newsViewMonth) {
		this.newsViewMonth = newsViewMonth;
	}

	public int getNewsViewWeek() {
		return this.newsViewWeek;
	}

	public void setNewsViewWeek(int newsViewWeek) {
		this.newsViewWeek = newsViewWeek;
	}

	public int getNewsViewDay() {
		return this.newsViewDay;
	}

	public void setNewsViewDay(int newsViewDay) {
		this.newsViewDay = newsViewDay;
	}

	public Date getNewsViewDate() {
		return this.newsViewDate;
	}

	public void setNewsViewDate(Date newsViewDate) {
		this.newsViewDate = newsViewDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public boolean isNewsIsOrigin() {
		return this.newsIsOrigin;
	}

	public void setNewsIsOrigin(boolean newsIsOrigin) {
		this.newsIsOrigin = newsIsOrigin;
	}

	public String getNewsSource() {
		return this.newsSource;
	}

	public void setNewsSource(String newsSource) {
		this.newsSource = newsSource;
	}

	public String getNewsAuthor() {
		return this.newsAuthor;
	}

	public void setNewsAuthor(String newsAuthor) {
		this.newsAuthor = newsAuthor;
	}

	public String getNewsThumbnail() {
		return this.newsThumbnail;
	}

	public void setNewsThumbnail(String newsThumbnail) {
		this.newsThumbnail = newsThumbnail;
	}

	public String getNewsPath() {
		return this.newsPath;
	}

	public void setNewsPath(String newsPath) {
		this.newsPath = newsPath;
	}

	public Integer getNewsPages() {
		return this.newsPages;
	}

	public void setNewsPages(Integer newsPages) {
		this.newsPages = newsPages;
	}

	public Date getPublishtime() {
		return this.publishtime;
	}

	public void setPublishtime(Date publishtime) {
		this.publishtime = publishtime;
	}

	public Set getNewsViewRankMonths() {
		return this.newsViewRankMonths;
	}

	public void setNewsViewRankMonths(Set newsViewRankMonths) {
		this.newsViewRankMonths = newsViewRankMonths;
	}

	public Set getNewsComments() {
		return this.newsComments;
	}

	public void setNewsComments(Set newsComments) {
		this.newsComments = newsComments;
	}

	public Set getNewsCategoryRels() {
		return this.newsCategoryRels;
	}

	public void setNewsCategoryRels(Set newsCategoryRels) {
		this.newsCategoryRels = newsCategoryRels;
	}

	public Set getNewsFollows() {
		return this.newsFollows;
	}

	public void setNewsFollows(Set newsFollows) {
		this.newsFollows = newsFollows;
	}

	public Set getNewsViewRankWeeks() {
		return this.newsViewRankWeeks;
	}

	public void setNewsViewRankWeeks(Set newsViewRankWeeks) {
		this.newsViewRankWeeks = newsViewRankWeeks;
	}

	public Set getNewsViewRankDays() {
		return this.newsViewRankDays;
	}

	public void setNewsViewRankDays(Set newsViewRankDays) {
		this.newsViewRankDays = newsViewRankDays;
	}

	public Set getNewsLikes() {
		return this.newsLikes;
	}

	public void setNewsLikes(Set newsLikes) {
		this.newsLikes = newsLikes;
	}

	public Set getNewsHeadlines() {
		return this.newsHeadlines;
	}

	public void setNewsHeadlines(Set newsHeadlines) {
		this.newsHeadlines = newsHeadlines;
	}

	public Set getNewsForwards() {
		return this.newsForwards;
	}

	public void setNewsForwards(Set newsForwards) {
		this.newsForwards = newsForwards;
	}

	public Set getTagNewsRels() {
		return this.tagNewsRels;
	}

	public void setTagNewsRels(Set tagNewsRels) {
		this.tagNewsRels = tagNewsRels;
	}

	public Set getNewsTops() {
		return this.newsTops;
	}

	public void setNewsTops(Set newsTops) {
		this.newsTops = newsTops;
	}

	public Set getNewsIndexPageTops() {
		return this.newsIndexPageTops;
	}

	public void setNewsIndexPageTops(Set newsIndexPageTops) {
		this.newsIndexPageTops = newsIndexPageTops;
	}

}
