package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

    private Integer tagId;
    private int tagCategoryId;
    private String tagName;
    private String status;
    private Date addtime;
    private Date updatetime;
    private String tagHref;
    private String tagSpell;
    private Set tagNewsRels = new HashSet(0);
    private Set tagLiveRels = new HashSet(0);

    public Tag() {
    }

    public Tag(int tagCategoryId, String tagName, String status, Date addtime,
               Date updatetime) {
        this.tagCategoryId = tagCategoryId;
        this.tagName = tagName;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Tag(int tagCategoryId, String tagName, String status, Date addtime,
               Date updatetime, String tagHref, String tagSpell, Set tagNewsRels,
               Set tagLiveRels) {
        this.tagCategoryId = tagCategoryId;
        this.tagName = tagName;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.tagHref = tagHref;
        this.tagSpell = tagSpell;
        this.tagNewsRels = tagNewsRels;
        this.tagLiveRels = tagLiveRels;
    }

    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    public int getTagCategoryId() {
        return this.tagCategoryId;
    }

    public void setTagCategoryId(int tagCategoryId) {
        this.tagCategoryId = tagCategoryId;
    }

    public String getTagName() {
        return this.tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getTagHref() {
        return this.tagHref;
    }

    public void setTagHref(String tagHref) {
        this.tagHref = tagHref;
    }

    public String getTagSpell() {
        return this.tagSpell;
    }

    public void setTagSpell(String tagSpell) {
        this.tagSpell = tagSpell;
    }

    public Set getTagNewsRels() {
        return this.tagNewsRels;
    }

    public void setTagNewsRels(Set tagNewsRels) {
        this.tagNewsRels = tagNewsRels;
    }

    public Set getTagLiveRels() {
        return this.tagLiveRels;
    }

    public void setTagLiveRels(Set tagLiveRels) {
        this.tagLiveRels = tagLiveRels;
    }

}
