package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TagCategory generated by hbm2java
 */
public class TagCategory implements java.io.Serializable {

    private Integer tagCategoryId;
    private String tagCategoryName;
    private String tagCategoryDesc;
    private String status;
    private Date addtime;
    private Date updatetime;

    public TagCategory() {
    }

    public TagCategory(String tagCategoryName, String status, Date addtime,
                       Date updatetime) {
        this.tagCategoryName = tagCategoryName;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public TagCategory(String tagCategoryName, String tagCategoryDesc,
                       String status, Date addtime, Date updatetime) {
        this.tagCategoryName = tagCategoryName;
        this.tagCategoryDesc = tagCategoryDesc;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Integer getTagCategoryId() {
        return this.tagCategoryId;
    }

    public void setTagCategoryId(Integer tagCategoryId) {
        this.tagCategoryId = tagCategoryId;
    }

    public String getTagCategoryName() {
        return this.tagCategoryName;
    }

    public void setTagCategoryName(String tagCategoryName) {
        this.tagCategoryName = tagCategoryName;
    }

    public String getTagCategoryDesc() {
        return this.tagCategoryDesc;
    }

    public void setTagCategoryDesc(String tagCategoryDesc) {
        this.tagCategoryDesc = tagCategoryDesc;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

}
