package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * TagLiveRel generated by hbm2java
 */
public class TagLiveRel implements java.io.Serializable {

    private TagLiveRelId id;
    private Live live;
    private Tag tag;

    public TagLiveRel() {
    }

    public TagLiveRel(TagLiveRelId id, Live live, Tag tag) {
        this.id = id;
        this.live = live;
        this.tag = tag;
    }

    public TagLiveRelId getId() {
        return this.id;
    }

    public void setId(TagLiveRelId id) {
        this.id = id;
    }

    public Live getLive() {
        return this.live;
    }

    public void setLive(Live live) {
        this.live = live;
    }

    public Tag getTag() {
        return this.tag;
    }

    public void setTag(Tag tag) {
        this.tag = tag;
    }

}
