package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * TagNewsRel generated by hbm2java
 */
public class TagNewsRel implements java.io.Serializable {

    private TagNewsRelId id;
    private News news;
    private Tag tag;

    public TagNewsRel() {
    }

    public TagNewsRel(TagNewsRelId id, News news, Tag tag) {
        this.id = id;
        this.news = news;
        this.tag = tag;
    }

    public TagNewsRelId getId() {
        return this.id;
    }

    public void setId(TagNewsRelId id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public Tag getTag() {
        return this.tag;
    }

    public void setTag(Tag tag) {
        this.tag = tag;
    }

}
