package com.n2cj.entity;

// Generated 2015-10-29 16:30:47 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Touhang generated by hbm2java
 */
public class Touhang implements java.io.Serializable {

	private int id;
	private String status;
	private String entry;
	private String target;
	private String zhisun;
	private String duokong;
	public String getDuokong() {
		return duokong;
	}

	public void setDuokong(String duokong) {
		this.duokong = duokong;
	}

	private String period;
	private Date addDate;

	public Touhang() {
	}

	public Touhang(int id, String status, String duokong, Date addDate) {
		this.id = id;
		this.status = status;
		this.duokong = duokong;
		this.addDate = addDate;
	}

	public Touhang(int id, String status, String entry, String target,
			String zhisun, String duokong, String period, Date addDate) {
		this.id = id;
		this.status = status;
		this.entry = entry;
		this.target = target;
		this.zhisun = zhisun;
		this.duokong = duokong;
		this.period = period;
		this.addDate = addDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getEntry() {
		return this.entry;
	}

	public void setEntry(String entry) {
		this.entry = entry;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getZhisun() {
		return this.zhisun;
	}

	public void setZhisun(String zhisun) {
		this.zhisun = zhisun;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

}
