package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

    private Integer roleId;
    private String roleName;
    private String roleDesc;
    private String status;
    private Date addtime;
    private Date updatetime;
    private Set userroleUserauthorityRels = new HashSet(0);
    private Set userRoleRels = new HashSet(0);

    public UserRole() {
    }

    public UserRole(String roleName, String status, Date addtime,
                    Date updatetime) {
        this.roleName = roleName;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public UserRole(String roleName, String roleDesc, String status,
                    Date addtime, Date updatetime, Set userroleUserauthorityRels,
                    Set userRoleRels) {
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.userroleUserauthorityRels = userroleUserauthorityRels;
        this.userRoleRels = userRoleRels;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleDesc() {
        return this.roleDesc;
    }

    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Set getUserroleUserauthorityRels() {
        return this.userroleUserauthorityRels;
    }

    public void setUserroleUserauthorityRels(Set userroleUserauthorityRels) {
        this.userroleUserauthorityRels = userroleUserauthorityRels;
    }

    public Set getUserRoleRels() {
        return this.userRoleRels;
    }

    public void setUserRoleRels(Set userRoleRels) {
        this.userRoleRels = userRoleRels;
    }

}
