package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAuthority generated by hbm2java
 */
public class UserAuthority implements java.io.Serializable {

    private Integer authorityId;
    private String authorityName;
    private String authorityDesc;
    private String status;
    private Date addtime;
    private Date updatetime;
    private Set userroleUserauthorityRels = new HashSet(0);

    public UserAuthority() {
    }

    public UserAuthority(String authorityName, String status, Date addtime,
                         Date updatetime) {
        this.authorityName = authorityName;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public UserAuthority(String authorityName, String authorityDesc,
                         String status, Date addtime, Date updatetime,
                         Set userroleUserauthorityRels) {
        this.authorityName = authorityName;
        this.authorityDesc = authorityDesc;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.userroleUserauthorityRels = userroleUserauthorityRels;
    }

    public Integer getAuthorityId() {
        return this.authorityId;
    }

    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    public String getAuthorityName() {
        return this.authorityName;
    }

    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }

    public String getAuthorityDesc() {
        return this.authorityDesc;
    }

    public void setAuthorityDesc(String authorityDesc) {
        this.authorityDesc = authorityDesc;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Set getUserroleUserauthorityRels() {
        return this.userroleUserauthorityRels;
    }

    public void setUserroleUserauthorityRels(Set userroleUserauthorityRels) {
        this.userroleUserauthorityRels = userroleUserauthorityRels;
    }

}
