package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * UserRoleRel generated by hbm2java
 */
public class UserRoleRel implements java.io.Serializable {

    private UserRoleRelId id;
    private User user;
    private UserRole userRole;

    public UserRoleRel() {
    }

    public UserRoleRel(UserRoleRelId id, User user, UserRole userRole) {
        this.id = id;
        this.user = user;
        this.userRole = userRole;
    }

    public UserRoleRelId getId() {
        return this.id;
    }

    public void setId(UserRoleRelId id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public UserRole getUserRole() {
        return this.userRole;
    }

    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

}
