package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer userId;
    private String userTelephone;
    private String userPassword;
    private String userEmail;
    private String userName;
    private String userQq;
    private String userSign;
    private String userGender;
    private String userOccupation;
    private String userInterests;
    private Date userBirth;
    private String userAvatar;
    private int userPosts;
    private int userUnreadMsg;
    private int userPoints;
    private int userLevel;
    private String status;
    private Date addtime;
    private Date updatetime;
    private String type;
    private Set newsComments = new HashSet(0);
    private Analyser analyser;
    private Set newsFollows = new HashSet(0);
    private Set newsLikes = new HashSet(0);
    private Set newsForwards = new HashSet(0);
    private Set userRoleRels = new HashSet(0);

    public User() {
    }

    public User(String userPassword, String userEmail, String userName,
                int userPosts, int userUnreadMsg, int userPoints, int userLevel,
                String status, Date addtime, Date updatetime, String type) {
        this.userPassword = userPassword;
        this.userEmail = userEmail;
        this.userName = userName;
        this.userPosts = userPosts;
        this.userUnreadMsg = userUnreadMsg;
        this.userPoints = userPoints;
        this.userLevel = userLevel;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.type = type;
    }

    public User(String userTelephone, String userPassword, String userEmail,
                String userName, String userQq, String userSign, String userGender,
                String userOccupation, String userInterests, Date userBirth,
                String userAvatar, int userPosts, int userUnreadMsg,
                int userPoints, int userLevel, String status, Date addtime,
                Date updatetime, String type, Set newsComments, Analyser analyser,
                Set newsFollows, Set newsLikes, Set newsForwards, Set userRoleRels) {
        this.userTelephone = userTelephone;
        this.userPassword = userPassword;
        this.userEmail = userEmail;
        this.userName = userName;
        this.userQq = userQq;
        this.userSign = userSign;
        this.userGender = userGender;
        this.userOccupation = userOccupation;
        this.userInterests = userInterests;
        this.userBirth = userBirth;
        this.userAvatar = userAvatar;
        this.userPosts = userPosts;
        this.userUnreadMsg = userUnreadMsg;
        this.userPoints = userPoints;
        this.userLevel = userLevel;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.type = type;
        this.newsComments = newsComments;
        this.analyser = analyser;
        this.newsFollows = newsFollows;
        this.newsLikes = newsLikes;
        this.newsForwards = newsForwards;
        this.userRoleRels = userRoleRels;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserTelephone() {
        return this.userTelephone;
    }

    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserQq() {
        return this.userQq;
    }

    public void setUserQq(String userQq) {
        this.userQq = userQq;
    }

    public String getUserSign() {
        return this.userSign;
    }

    public void setUserSign(String userSign) {
        this.userSign = userSign;
    }

    public String getUserGender() {
        return this.userGender;
    }

    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    public String getUserOccupation() {
        return this.userOccupation;
    }

    public void setUserOccupation(String userOccupation) {
        this.userOccupation = userOccupation;
    }

    public String getUserInterests() {
        return this.userInterests;
    }

    public void setUserInterests(String userInterests) {
        this.userInterests = userInterests;
    }

    public Date getUserBirth() {
        return this.userBirth;
    }

    public void setUserBirth(Date userBirth) {
        this.userBirth = userBirth;
    }

    public String getUserAvatar() {
        return this.userAvatar;
    }

    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    public int getUserPosts() {
        return this.userPosts;
    }

    public void setUserPosts(int userPosts) {
        this.userPosts = userPosts;
    }

    public int getUserUnreadMsg() {
        return this.userUnreadMsg;
    }

    public void setUserUnreadMsg(int userUnreadMsg) {
        this.userUnreadMsg = userUnreadMsg;
    }

    public int getUserPoints() {
        return this.userPoints;
    }

    public void setUserPoints(int userPoints) {
        this.userPoints = userPoints;
    }

    public int getUserLevel() {
        return this.userLevel;
    }

    public void setUserLevel(int userLevel) {
        this.userLevel = userLevel;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set getNewsComments() {
        return this.newsComments;
    }

    public void setNewsComments(Set newsComments) {
        this.newsComments = newsComments;
    }

    public Analyser getAnalyser() {
        return this.analyser;
    }

    public void setAnalyser(Analyser analyser) {
        this.analyser = analyser;
    }

    public Set getNewsFollows() {
        return this.newsFollows;
    }

    public void setNewsFollows(Set newsFollows) {
        this.newsFollows = newsFollows;
    }

    public Set getNewsLikes() {
        return this.newsLikes;
    }

    public void setNewsLikes(Set newsLikes) {
        this.newsLikes = newsLikes;
    }

    public Set getNewsForwards() {
        return this.newsForwards;
    }

    public void setNewsForwards(Set newsForwards) {
        this.newsForwards = newsForwards;
    }

    public Set getUserRoleRels() {
        return this.userRoleRels;
    }

    public void setUserRoleRels(Set userRoleRels) {
        this.userRoleRels = userRoleRels;
    }

}
