package com.n2cj.entity;

// Generated 2015-9-6 10:20:22 by Hibernate Tools 4.3.1

/**
 * UserroleUserauthorityRel generated by hbm2java
 */
public class UserroleUserauthorityRel implements java.io.Serializable {

    private UserroleUserauthorityRelId id;
    private UserAuthority userAuthority;
    private UserRole userRole;

    public UserroleUserauthorityRel() {
    }

    public UserroleUserauthorityRel(UserroleUserauthorityRelId id,
                                    UserAuthority userAuthority, UserRole userRole) {
        this.id = id;
        this.userAuthority = userAuthority;
        this.userRole = userRole;
    }

    public UserroleUserauthorityRelId getId() {
        return this.id;
    }

    public void setId(UserroleUserauthorityRelId id) {
        this.id = id;
    }

    public UserAuthority getUserAuthority() {
        return this.userAuthority;
    }

    public void setUserAuthority(UserAuthority userAuthority) {
        this.userAuthority = userAuthority;
    }

    public UserRole getUserRole() {
        return this.userRole;
    }

    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

}
